name: CI
on: [push, pull_request]

permissions: write-all

jobs:
  test:
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for actions/checkout to fetch code
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [22.x, 23.x, 24.x]

    steps:
    - uses: actions/checkout@v6
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: |
        pnpm install --frozen-lockfile
        sudo pnpm exec playwright install-deps
        pnpm exec playwright install

    - name: Lint
      run: pnpm run lint

    - name: Run Test
      run: pnpm run coverage:ci

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: ./coverage/lcov.info
        format: lcov
        flag-name: run-${{ matrix.node-version }}
        parallel: true
        fail-on-error: false
        
  send_coverage:
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls
      # https://github.com/marketplace/actions/coveralls-github-action
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
        fail-on-error: false

  release:
    needs: send_coverage
    runs-on: ubuntu-latest
    if: contains('refs/heads/next refs/heads/latest', github.ref)
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        id: publish
        run: pnpm run release

      - name: Deploy
        shell: bash
        run: |
          git remote set-url origin https://netil:${{ secrets.GH_TOKEN }}@github.com/naver/billboard.js.git > /dev/null 2>&1
          bash ./config/deploy.sh
        # https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
        if: github.ref == 'refs/heads/latest' && steps.publish.conclusion == 'success'
