name: Nightly Build

on:
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
  schedule:
  - cron: "30 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        shell: bash
        run: bash ./config/deploy-nightly.sh setup

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm config set package-lock false
          npm install --save --legacy-peer-deps

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        shell: bash
        run: bash ./config/deploy-nightly.sh build
